apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deploy
  labels:
    name: vote-app-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote-app-pod
      app: voting-app

  template:
    metadata:
      name: vote-app-pod
      labels:
        name: vote-app-pod
        app: voting-app
    spec:
      containers:
        - name: vote-app
          image: brsahu/vote-app:v1
          ports:
            - containerPort: 80
